### ISSUE TITLE
Project build error: Non-readable POM <path>/pom.xml: input contained no data

### ISSUE THREAD

**Issue by lhollyer** [TIBCOSoftware/bw6-plugin-maven#231]
Maven Plugin version:

Maven version: 2.0.0 and 2.1.0

Product : TIBCO BW6.5.0

Component: Maven build plugin

**Steps to reproduce the issue:**
1. Installed BW6 plugin into BW6.5.0 
2. Created a new Application and Application Module
3. Generate POM for Application (thus generating POM for Application Module)

**Describe the results you received:**
Application POM generates OK but the Application Module POM contains no data. I've tried it in a new workspace and with a different version of the Maven plugin but I'm still getting the same result.

<img width="571" alt="screenshot 2018-12-20 at 13 21 56" src="https://user-images.githubusercontent.com/32904354/50287376-718acb80-045a-11e9-87e5-8a6f373a1e43.png">

**Additional information you deem important (e.g. issue happens only occasionally):**
My application is a very simple application which runs a timer to log a message set in the module properties of a shared module.

**Comment by alexandrev** [comment]
Hi @lhollyer , could you paste the content of the pom.xml file?

**Comment by lhollyer** [comment]
Hi @alexandrev - pom.xml with the error is empty. Application pom.xml is as follows:

<img width="1057" alt="screenshot 2018-12-20 at 15 16 59" src="https://user-images.githubusercontent.com/32904354/50292938-588a1680-046a-11e9-99bc-7981739db746.png">


`<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.tibco.bw</groupId>
    <artifactId>maven-example.parent</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <relativePath>../maven-example.parent</relativePath>
  </parent>
  <artifactId>maven-example</artifactId>
  <packaging>bwear</packaging>
  <properties>
    <skipTests>false</skipTests>
    <bw.Home></bw.Home>
    <project.type>None</project.type>
    <failIfNoTests>false</failIfNoTests>
    <tibco.Home></tibco.Home>
  </properties>
  <build>
    <plugins>
      <plugin>
        <groupId>com.tibco.plugins</groupId>
        <artifactId>bw6-maven-plugin</artifactId>
        <version>2.1.0</version>
        <extensions>true</extensions>
      </plugin>
    </plugins>
  </build>
  <reporting>
    <plugins>
      <plugin>
        <groupId>com.tibco.plugins</groupId>
        <artifactId>bw6-maven-plugin</artifactId>
        <version>2.1.0</version>
      </plugin>
    </plugins>
  </reporting>
</project>`

Parent pom.xml:

`<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.tibco.bw</groupId>
  <artifactId>maven-example.parent</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <packaging>pom</packaging>
  <modules>
    <module>../maven-example-bsm</module>
    <module>../maven-example.module</module>
    <module>../maven-example</module>
  </modules>
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-site-plugin</artifactId>
        <version>3.7.1</version>
      </plugin>
    </plugins>
  </build>
</project>
`

**Comment by ankitapandey1** [comment]
Hi @lhollyer 
I am not able to replicate this issue I tried with TIBCO BW6.5.0 and Maven version 2.1.0. 
As you mentioned this issue happens only occasionally I think it could be synchronization issue  , So when you face this issue again just clean the project and check. 
If the issue persist let me know.

**Comment by ashish22795** [comment]
Hi,

Facing the same issue.
Any suggestion would be helpful.

Thanks and Regards,
Ashish

**Comment by SujataDarekar** [comment]
@ashish22795 As discussed on call POM file getting generated successfully by switching the workspace

**Comment by alexandrev** [comment]
It seems that disabling maven nature and re-enable it in the module that has the issue. make the issue gone. But this should be solved at the plugin level. So please, we should reopen this issue.

**Comment by ankitapandey1** [comment]
Hi @ashish22795 

This issue is fixed in Maven version: 2.1.1 please try installing latest maven version and check.

Thanks!!

**Comment by ashish22795** [comment]
Hi @ankitapandey1 ,

Thanks a lot!
I'll check with the latest Maven verison.

Regards,
Ashish

**Comment by shivrya** [comment]
add <maven-jar-plugin.version>3.1.1</maven-jar-plugin.version> under <properties>

**Comment by ashharr** [comment]
I am getting this error. Reinstalling maven doesn't work still facing the same issue. 

```
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-readable POM C:\Users\.m2\repository\org\apache\logging\logging-parent\3\logging-parent-3.pom: input contained no data @ C:\Users\.m2\repository\org\apache\logging\logging-parent\3\logging-parent-3.pom
[FATAL] Non-readable POM C:\Users\.m2\repository\io\prometheus\simpleclient_bom\0.10.0\simpleclient_bom-0.10.0.pom: input contained no data @ C:\Users\59268\.m2\repository\io\prometheus\simpleclient_bom\0.10.0\simpleclient_bom-0.10.0.pom
[FATAL] Non-readable POM C:\Users\.m2\repository\io\r2dbc\r2dbc-bom\Arabba-SR10\r2dbc-bom-Arabba-SR10.pom: input contained no data @ C:\Users\.m2\repository\io\r2dbc\r2dbc-bom\Arabba-SR10\r2dbc-bom-Arabba-SR10.pom
[FATAL] Non-readable POM C:\Users\.m2\repository\org\springframework\spring-framework-bom\5.3.9\spring-framework-bom-5.3.9.pom: input contained no data @ C:\Users\59268\.m2\repository\org\springframework\spring-framework-bom\5.3.9\spring-framework-bom-5.3.9.pom
```
